<?php

return array(
	''                 => 'None',
	'arrow'            => 'Arrow',
	'arrow-invert'     => 'Arrow - Invert',
	'arrow-2'          => 'Arrow 2',
	'arrow-2-invert'   => 'Arrow 2 - Invert',
	'book'             => 'Book',
	'book-invert'      => 'Book - Invert',
	'curve'            => 'Curve',
	'curve-invert'     => 'Curve - Invert',
	'curve-2'          => 'Curve 2',
	'curve-2-invert'   => 'Curve 2 - Invert',
	'curve-opacity'    => 'Curve opacity',
	'fan'              => 'Fan',
	'tilt'             => 'Tilt',
	'triangle'         => 'Triangle',
	'triangle-invert'  => 'Triangle - Invert',
	'triangle-opacity' => 'Triangle opacity',
	'waves'            => 'Waves',
	'waves-opacity'    => 'Waves opacity',
	'waves-opacity-2'  => 'Waves opacity 2',
	'waves-opacity-3'  => 'Waves opacity 3',
);
